use_frameworks!

platform :ios, '12.0'

target 'AppsOnAir-AppSync_Example' do
  pod 'AppsOnAir-AppSync', :path => '../'


  target 'AppsOnAir-AppSync_Tests' do
    inherit! :search_paths

    
  end
end
